version:  '3.3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
    - '3636:3306'
    volumes:
      - './mysql:/var/lib/mysql'

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
    - '.:/usr/src/app'  
    - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
    - '8080:80'
    - '12346:12345'

  php:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    ports:
      - '12345:12345'
    links:
      - mysql